favicon: null
name: fT
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.234767
  brandStrength: 0.8799283
  lightness: 0.1792115
  brandColors:
    - '#000000'
    - '#E8E2E7'
    - '#867E83'
    - '#554B54'
    - '#FDA601'
  rhythmicContrast: 0.8870968
typography_spectrum: 0.5232975
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
